[package]
name = "gothic-wasm4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm4 = { path = "wasm4" }
buddy-alloc = "0.4"
